#!/usr/bin/env python3
"""Data audit entrypoint."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(REPO_ROOT / "src"))

from examples.bspm.bspm_harness.data.bspm_superfile import (
    audit_superfile_records,
    audit_superfile_source,
    node_indices,
    node_label_rows,
    parse_node_label_xlsx,
    write_csv,
)


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit dataset integrity.")
    parser.add_argument("--config", default="configs/base.yaml", help="Path to experiment config.")
    parser.add_argument("--raw-path", help="Path to a Superfile zip archive, directory, or file.")
    parser.add_argument("--node-label-path", help="Path to node_label.xlsx.")
    parser.add_argument("--output-dir", help="Directory for audit CSV outputs.")
    parser.add_argument("--max-records", type=int, help="Limit records for a quick smoke audit.")
    args = parser.parse_args()

    config = Path(args.config)
    if not config.exists():
        parser.error(f"config not found: {config}")

    raw_path = args.raw_path or _read_config_value(config, "raw_path")
    node_label_path = args.node_label_path or _read_config_value(config, "node_label_path")
    if not raw_path:
        print(f"Data audit placeholder passed for {config}; no raw_path configured.")
        return 0

    summary = audit_superfile_source(raw_path, max_records=args.max_records)
    print(f"Data audit passed for {config}.")
    for key, value in summary.items():
        print(f"{key}: {value}")

    if node_label_path:
        labels = parse_node_label_xlsx(node_label_path)
        print(f"node_label_rows: {len(labels)}")
        print(f"node_120_count: {len(node_indices(labels, 'node_120'))}")
        print(f"node_352_count: {len(node_indices(labels, 'node_352'))}")

    if args.output_dir:
        output_dir = Path(args.output_dir)
        record_rows = audit_superfile_records(raw_path, max_records=args.max_records)
        write_csv(output_dir / "dal_bspm_record_audit.csv", record_rows)
        if node_label_path:
            write_csv(output_dir / "dal_bspm_node_labels.csv", node_label_rows(labels))
        _write_output_readme(output_dir, raw_path, node_label_path, summary)
        print(f"audit_csv_dir: {output_dir}")
    return 0


def _read_config_value(path: Path, key: str) -> str | None:
    prefix = f"{key}:"
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith(prefix):
            value = stripped[len(prefix) :].strip()
            return value or None
    return None


def _write_output_readme(
    output_dir: Path, raw_path: str, node_label_path: str | None, summary: dict[str, object]
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    node_label_line = node_label_path or "<not provided>"
    (output_dir / "README.md").write_text(
        "\n".join(
            [
                "# Dal_BSPM Data Audit",
                "",
                "Generated by `examples/bspm/scripts/audit_data.py`.",
                "",
                f"- Raw path: `{raw_path}`",
                f"- Node label path: `{node_label_line}`",
                f"- Record count: `{summary['record_count']}`",
                f"- Sampling intervals ms: `{summary['sampling_intervals_ms']}`",
                f"- Sample count range: `{summary['sample_count_min']}` to `{summary['sample_count_max']}`",
                f"- Node potential range: `{summary['node_potential_min']}` to `{summary['node_potential_max']}`",
                f"- `9999` count: `{summary['node_9999_count']}`",
                f"- `-9999` count: `{summary['node_minus_9999_count']}`",
                "",
                "CSV outputs:",
                "",
                "- `dal_bspm_record_audit.csv`: one row per parsed Superfile record",
                "- `dal_bspm_node_labels.csv`: one row per 0-based torso node",
                "",
                "The v1 reconstruction data contract is `k` selected nodes from the `node_120` set to all `node_120` targets.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    raise SystemExit(main())
